name: Release

on:
  push:
    branches:
      - main

jobs:
  lint-test:
    uses: ./.github/workflows/lint-test.yml

  release:
    name: Release Python Package
    runs-on: ubuntu-latest
    needs: lint-test

    # TODO: remove unnecessary permissions
    permissions:
        contents: write
        actions: write
        checks: write
        issues: write
        discussions: write
        packages: write
        pull-requests: write
        repository-projects: write
        statuses: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          pip install -e .
          pip install -r requirements.txt

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Install build tools
        run: |
          pip install build twine

      - name: Build package
        run: |
          python -m build

      - name: Semantic release
        run: |
          npm install semantic-release
          npx semantic-release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
